### ISSUE TITLE
How to reduce training loss

### ISSUE THREAD

**Issue by MTK10152** [2019-dl-training-program/Lab4#13]
Firstly, the training loss of reconstruction without KL loss can be almost zero. But, I use monotonic approach to train VAE and the reconstruction training loss is bigger when KL loss get smaller.  Is it normal? How to reduce training loss of reconstruction with KL loss?

**Comment by robert80203** [comment]
That is normal. You have to make a balance between reconstruction loss and KL loss. To get that balance, there are two training methods you should use (mentioned in pdf) and the kl weight values you should try by yourself.
