### ISSUE TITLE
How to do testing with BLEU-4 score?

### ISSUE THREAD

**Issue by WenChouWu** [2019-dl-training-program/Lab4#14]
Hello TA,

For the BLEU-4 score testing process, should I send the input (ex. 'flared') to the encoder with related tense (ex. past) and add the tense condition with generated hidden vector as the input of decoder to predict the tense conversion? Am I correct?

input: flared
target: flare
prediction: flare

**Comment by robert80203** [comment]
Yes

**Comment by WenChouWu** [comment]
For the BLEU-4 score test, is it a 'must-be' to take the words in test.text for testing? Could I select the words in train.txt randomly with the corresponding tense for testing?

**Comment by robert80203** [comment]
Yes. You must use words in test.txt  as your testing data.
