### ISSUE TITLE
question for dataset

### ISSUE THREAD

**Issue by MTK10152** [2019-dl-training-program/Lab4#3]
What's the meaning as following in dataset readme.txt,
Here are to details of the file:

sp -> p
sp -> pg
sp -> tp
sp -> tp
p  -> tp
sp -> pg
p  -> sp
pg -> sp
pg -> p
pg -> tp

**Comment by robert80203** [comment]
In the readme.txt, the first point (1. train.txt) explains the notations of sp, tp, pg and p

For example, in the first line of the train.txt
sp -> p
and in the first line of the test.txt
abandon abandoned

It means the tense conversion from simple present (abandon) to past (abandoned)
