### ISSUE TITLE
How to add conditional label

### ISSUE THREAD

**Issue by MTK10152** [2019-dl-training-program/Lab4#4]
Can I concatenate initial zero hidden part with conditional label part into nn.embedding as input of encoder?

And can I concatenate latent vector part with conditional label part into nn.linear as input of decoder?

**Comment by robert80203** [comment]
For the encoder part, you should concatenate zero hidden vector with conditional label as the initial hidden vector for GRU (so now your input to the encoder will be the output of the nn.embedding and the initial hidden), and the decoder part is the same as you said.
