### ISSUE TITLE
How to implement ground truth vector in CVAE

### ISSUE THREAD

**Issue by MTK10152** [2019-dl-training-program/Lab4#7]
In the PPT, there is example as following.

input words = 'A,B' 
output words = 'C,D,<EOS>'

I try to form a target vector, but I found there are different length in above sample. In previous tutorial LAB, the predict vector is the same length as label vector. I know the VAE is a reconstruction process, the ground truth should be input sequence, but I can not get this concept from above sample.

**Comment by robert80203** [comment]
The input words will be 'A, B' and the output words will also be 'A, B' (in the example I use C, D)
 In the implementation, the input for the encoder will be 'A, B' and the input for the decoder will be 'SOS, A, B' and the expected target will be 'A, B, EOS'
As a result, the length of your inputs for encoder and decoder will not be the same.
