### ISSUE TITLE
Latent parameters training using LSTM

### ISSUE THREAD

**Issue by WenChouWu** [2019-dl-training-program/Lab4#8]
Hi TA,

When using LSTM for decoder/encoder, the hidden output of encoder using LSTM is (h_n, c_n) and then we need to use nn.Linear to map to the dimension in latent space. Do you suggest to use separated nn.Linear for h_n and c_n or shared nn.Linear? Besides, do we add condition vector to both h_n and c_n?

**Comment by robert80203** [comment]
I think you may try all of the settings you mentioned. In my implementation, I only take h_n to the nn.Linear and add condition to the h_n. c_n in the decoder part will be a new zero vector.

**Comment by WenChouWu** [comment]
I'm still a little confusing about concatenating the condition into hidden with nn.Embedding. For, example, the tense_state is 4 in this Lab, and I make the projection with nn.Embedding(4,10) and then concatenates to the hidden with size [1, batch_size, 512]. So the updated hidden vector used as input to encoder/decoder is with size of [1, batch_size, 512+10]. Am I correct?

**Comment by robert80203** [comment]
If the encoder hidden size is 512, then the initial hidden should be [1, batch_size, 502] since you have to concatenate your condition [10] to the initial hidden vector
