### ISSUE TITLE
What's the input of condition embedding 

### ISSUE THREAD

**Issue by MTK10152** [2019-dl-training-program/Lab4#9]
Does input size use (batch_size, 1) for condition embedding if I use dictionary to label condition?

Or I need to use one-hot for condition and feed into condition embedding as size of (batch_size, one-hot_size)?

And there has two nn.embedding for input data of encoder and decoder. Are they different embedding weight with condition embedding? If yes, do we need four nn.embedding in encoder and decoder?

**Comment by robert80203** [comment]
If you use condition embedding, then the input will be (batch_size, 1). If you use one-hot, your condition is just one-hot vector.
The embedding weights in the encoder and decoder are different for convenience. As a result, we need total 4 embedding layers
